package com.example.bob.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF845400)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDDB6)
val md_theme_light_onPrimaryContainer = Color(0xFF2A1800)
val md_theme_light_secondary = Color(0xFF954A02)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDCC6)
val md_theme_light_onSecondaryContainer = Color(0xFF301400)
val md_theme_light_tertiary = Color(0xFF53643E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD6E9B9)
val md_theme_light_onTertiaryContainer = Color(0xFF121F03)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFFa38460)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1F1B16)
val md_theme_light_surfaceVariant = Color(0xFFF0E0D0)
val md_theme_light_onSurfaceVariant = Color(0xFF504539)
val md_theme_light_outline = Color(0xFF827568)
val md_theme_light_inverseOnSurface = Color(0xFFF9EFE7)
val md_theme_light_inverseSurface = Color(0xFF35302A)
val md_theme_light_inversePrimary = Color(0xFFFFB95B)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF845400)
val md_theme_light_outlineVariant = Color(0xFFD4C4B4)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB95B)
val md_theme_dark_onPrimary = Color(0xFF462A00)
val md_theme_dark_primaryContainer = Color(0xFF643F00)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDDB6)
val md_theme_dark_secondary = Color(0xFFFFB785)
val md_theme_dark_onSecondary = Color(0xFF502400)
val md_theme_dark_secondaryContainer = Color(0xFF723700)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDCC6)
val md_theme_dark_tertiary = Color(0xFFBACD9F)
val md_theme_dark_onTertiary = Color(0xFF263514)
val md_theme_dark_tertiaryContainer = Color(0xFF3C4C28)
val md_theme_dark_onTertiaryContainer = Color(0xFFD6E9B9)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1F1B16)
val md_theme_dark_onBackground = Color(0xFFEBE1D9)
val md_theme_dark_surface = Color(0xFF1F1B16)
val md_theme_dark_onSurface = Color(0xFFEBE1D9)
val md_theme_dark_surfaceVariant = Color(0xFF504539)
val md_theme_dark_onSurfaceVariant = Color(0xFFD4C4B4)
val md_theme_dark_outline = Color(0xFF9C8E80)
val md_theme_dark_inverseOnSurface = Color(0xFF1F1B16)
val md_theme_dark_inverseSurface = Color(0xFFEBE1D9)
val md_theme_dark_inversePrimary = Color(0xFF845400)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB95B)
val md_theme_dark_outlineVariant = Color(0xFF504539)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFF0CDA5)
val Customcolor1 = Color(0xFFB0735F)
val light_Customcolor1 = Color(0xFF9B4426)
val light_onCustomcolor1 = Color(0xFFFFFFFF)
val light_Customcolor1Container = Color(0xFFFFDBD0)
val light_onCustomcolor1Container = Color(0xFF390C00)
val dark_Customcolor1 = Color(0xFFFFB59D)
val dark_onCustomcolor1 = Color(0xFF5D1800)
val dark_Customcolor1Container = Color(0xFF7C2E11)
val dark_onCustomcolor1Container = Color(0xFFFFDBD0)