package com.baldo.bob.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF954A02)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDCC6)
val md_theme_light_onPrimaryContainer = Color(0xFF301400)
val md_theme_light_secondary = Color(0xFF9B4426)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDBD0)
val md_theme_light_onSecondaryContainer = Color(0xFF390C00)
val md_theme_light_tertiary = Color(0xFF5F6134)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE5E6AE)
val md_theme_light_onTertiaryContainer = Color(0xFF1C1D00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFFa38460)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF201A17)
val md_theme_light_surfaceVariant = Color(0xFFF4DED3)
val md_theme_light_onSurfaceVariant = Color(0xFF52443B)
val md_theme_light_outline = Color(0xFF84746A)
val md_theme_light_inverseOnSurface = Color(0xFFFBEEE8)
val md_theme_light_inverseSurface = Color(0xFF362F2B)
val md_theme_light_inversePrimary = Color(0xFFFFB785)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF954A02)
val md_theme_light_outlineVariant = Color(0xFFD7C3B7)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB785)
val md_theme_dark_onPrimary = Color(0xFF502400)
val md_theme_dark_primaryContainer = Color(0xFF723700)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDCC6)
val md_theme_dark_secondary = Color(0xFFFFB59D)
val md_theme_dark_onSecondary = Color(0xFF5D1800)
val md_theme_dark_secondaryContainer = Color(0xFF7C2E11)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDBD0)
val md_theme_dark_tertiary = Color(0xFFC9CA94)
val md_theme_dark_onTertiary = Color(0xFF31320A)
val md_theme_dark_tertiaryContainer = Color(0xFF47491F)
val md_theme_dark_onTertiaryContainer = Color(0xFFE5E6AE)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF17191A)
//val md_theme_dark_background = Color(0xFF201A17)
val md_theme_dark_onBackground = Color(0xFFECE0DA)
val md_theme_dark_surface = Color(0xFF201A17)
val md_theme_dark_onSurface = Color(0xFFECE0DA)
val md_theme_dark_surfaceVariant = Color(0xFF52443B)
val md_theme_dark_onSurfaceVariant = Color(0xFFD7C3B7)
val md_theme_dark_outline = Color(0xFF9F8D83)
val md_theme_dark_inverseOnSurface = Color(0xFF201A17)
val md_theme_dark_inverseSurface = Color(0xFFECE0DA)
val md_theme_dark_inversePrimary = Color(0xFF954A02)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB785)
val md_theme_dark_outlineVariant = Color(0xFF52443B)


val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFE6BA9E)
val Customcolor1 = Color(0xFFB0735F)
val light_Customcolor1 = Color(0xFF9B4426)
val light_onCustomcolor1 = Color(0xFFFFFFFF)
val light_Customcolor1Container = Color(0xFFFFDBD0)
val light_onCustomcolor1Container = Color(0xFF390C00)
val dark_Customcolor1 = Color(0xFFFFB59D)
val dark_onCustomcolor1 = Color(0xFF5D1800)
val dark_Customcolor1Container = Color(0xFF7C2E11)
val dark_onCustomcolor1Container = Color(0xFFFFDBD0)